version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: myproject-db-container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: asdf1234
      MARIADB_DATABASE: myproject
    ports:
      - "3306:3306"
    volumes:
      - ./myproject-backend/db/db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 9

  backend:
    build:
      context: ./myproject-backend
      dockerfile: Dockerfile
    container_name: myproject-backend-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://myproject-db-container:3306/myproject?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=asdf1234
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./myproject-frontend
      dockerfile: Dockerfile
    container_name: myproject-frontend-container
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend